version: '3.1'

services:
  mongodb:
    image: mongo
    volumes:
      - './data:/data/db'

  url-shortener:
    image: url-shortener:0.0.1-SNAPSHOT
    ports:
      - "9999:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb

networks:
  default:
    name: url-shortener-network
