version: '3.1'

services:
  redirecter:
    image: simonpic/url-shortener-redirect
    ports:
      - "8090:8090"
    depends_on:
      - mongodb-dev
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb-dev

  mongodb-dev:
    image: mongo
    ports:
      - "27017:27017"
