name: Contact Manager CI/CD workflow

on:
  push:
    branches:
      - master

env:
  DOCKER_REPOSITORY: simonpic/url-shortener

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Run unit tests
        run: ./mvnw test

      - name: Run integration test
        run: ./mvnw verify

  build-and-release-image:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Get image name
        run: echo ::set-output name=image_name::$DOCKER_REPOSITORY:$(git rev-parse --short "$GITHUB_SHA")
        id: get-image-name

      - name: Build image
        run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ steps.get-image-name.outputs.image_name }}

      - name: Login to Docker Hub
        run: echo $DOCKER_HUB_TOKEN | docker login -u simonpic --password-stdin
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image to registry
        run: docker push ${{ steps.get-image-name.outputs.image_name }}
